# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.

name: Deploy ASF site

on:
  push:
    branches:
#      - master
      - "avro-3686-asf.yaml-docs"
    tags-ignore:
      - "release-**-rc**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Set target branch
        id: target-branch
        run: |
          set -x
          if test '${{ github.ref }}' = 'refs/heads/avro-3686-asf.yaml-docs'; then
            echo "value=site-staging" >> $GITHUB_OUTPUT
          elif test '${{ github.ref_type }}' = 'tag'; then
            echo "value=site-production" >> $GITHUB_OUTPUT
          else
            echo "Unsupported input: ${{ github.ref }} / ${{ github.ref_type }}"
            exit 1
          fi

      - name: Checkout docs sources
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout docs target branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.target-branch.outputs.value }}
          path: docs-target

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        run: |
          set -x
          cd doc
          npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.108.0
          extended: true

      - name: Build docs
        run: |
          set -x
          cd doc
          hugo --minify --destination ../website

      # TODO build the C/C++/C# docs

      - name: Copy & push the generated HTML
        run: |
          set -x
          cd docs-target
          # delete anything but: 1) '.'; 2) '..'; 3) .git/
          find ./ | grep -vE "^./$|^../$|^./.git" | xargs rm -rf
          cp ../.asf.yaml .
          cp -r ../website/* .
          # TODO copy the C/C++/C# docs
          if [ "$(git status --porcelain)" != "" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add --all
            git commit -m 'Publish built docs triggered by ${{ github.sha }}'
            git push || git push --force
          fi
